version: "2"

linters:
  default: standard
  enable:
    - gocritic
  settings:
    errcheck:
      check-type-assertions: true
      check-blank: true
    gocyclo:
      min-complexity: 20
    gocritic:
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - performance
        - style
  exclusions:
    rules:
      - linters:
          - goconst
          - funlen
          - dupl
          - unused
          - unparam
        path: "_test.go"
      - linters:
          - errcheck
          - gosec
        path: "example_"
